### ISSUE TITLE
direct kernel boot

### ISSUE THREAD

**Issue by gssxd** [intel/nemu#205]
Does NEMU support ubuntu or Centos for direct kernel boot?

**Comment by wkozaczuk** [comment]
Hi,

Couple of days ago we just got OSv unikernel officially supported on [Firecracker](https://groups.google.com/forum/#!topic/osv-dev/rO6m1yMJbZ0) and OSv boots as low as 10ms (5ms on Firecracker side + 5ms on OSv side). I think that Firecracker can boot so fast because of direct uncompressed Linux boot (64-bit vmlinux ELF). BTW linux itself boots at around 125ms on [firecracker](https://github.com/firecracker-microvm/firecracker).

I would love to get OSv boot so fast on NEMU as well. Any plans to support similar type of Linux boot protocol?

**Comment by yangzhon** [comment]
@gssxd,

In order to upstream NEMU, we dropped the skip-bios solution(direct elf kernel boot) from NEMU before, the current NEMU can only support bzImage, thanks!

**Comment by yangzhon** [comment]
@wkozaczuk ,

Thanks for comments!
In fact, NEMU support direct boot before, but solution is a little hack, in order to upstream NEMU, we dropped the skip-bios solution.

If you have interesting in our skip-bios solution, you can ref below code 
https://github.com/kata-containers/qemu/tree/qemu-lite-2.11.0

If you have better solution, welcome to introduce to us. thanks!

**Comment by stefano-garzarella** [comment]
Hi all,
QEMU 4.0 will be able to boot directly into the uncompressed Linux kernel binary with minimal firmware involvement using the PVH entry point (you should enable CONFIG_PVH=y in Linux config file).
The PVH ABI was initially developed for Xen guests, but with latest changes, QEMU will be able to use that same entry point for booting KVM guests.

To boot the PVH kernel image, you can use the standard -kernel parameter specifying the path to the vmlinux image:
qemu-system-x86_64 -machine pc,accel=kvm \
    -kernel /path/to/vmlinux \
    -drive file=/path/to/rootfs.ext2,if=virtio,format=raw \
    -append 'root=/dev/vda console=ttyS0' -vga none -display none \
    -serial mon:stdio

QEMU patches:
https://www.mail-archive.com/qemu-devel@nongnu.org/msg587312.html
https://www.mail-archive.com/qemu-devel@nongnu.org/msg588561.html

Linux patches:
https://lkml.org/lkml/2018/12/14/1330

**Comment by yangzhon** [comment]
@stefano-garzarella

Thanks for sharing info!
We will rebase NEMU based on Qemu 4.0 and do comparable test with you did in below link
https://lists.gnu.org/archive/html/qemu-devel/2018-12/msg00200.html

**Comment by stefano-garzarella** [comment]
@yangzhon great! Let me know if you need some help to test it.
Here some numbers that I took last month with PVH:
* QEMU (q35) + SeaBIOS + bzImage
 qemu_init_end: 36.072056
 linux_start_kernel: 114.669522 (+78.597466)
 linux_start_user: 191.748567 (+77.079045)

* QEMU (q35) + qboot + bzImage
 qemu_init_end: 36.443638
 linux_start_kernel: 106.73115 (+70.287512)
 linux_start_user: 184.575531 (+77.844381)

* QEMU (q35) + SeaBIOS + vmlinux(PVH)
 qemu_init_end: 51.588200
 linux_start_kernel: 62.124665 (+10.536465)
 linux_start_user: 139.460582 (+77.335917)

* QEMU (q35) + qboot + vmlinux(PVH)
 qemu_init_end: 51.877656
 linux_start_kernel: 56.710735 (+4.833079)
 linux_start_user: 133.808972 (+77.098237)

* QEMU-lite (fw=off) + vmlinux
 qemu_init_end: 31.205082
 linux_start_kernel: 31.751789 (+0.546707)
 linux_start_user: 121.256293 (+89.504504)

Tracepoints:
- qemu_init_end: first kvm_entry (i.e. QEMU initialization has finished)
- linux_start_kernel: first entry of the Linux kernel (start_kernel())
- linux_start_user: before starting the init process

**Comment by yangzhon** [comment]
@stefano-garzarella

Thanks a lot!

For below test, did you use configurable Seabios and specific guest kernel? This test result is really good for qemu to start bzImage with Seabios.

QEMU (q35) + SeaBIOS + bzImage
qemu_init_end: 36.072056
linux_start_kernel: 114.669522 (+78.597466)
linux_start_user: 191.748567 (+77.079045)

**Comment by stefano-garzarella** [comment]
@yangzhon 

I used the SeaBIOS mainline (https://github.com/coreboot/seabios.git) with a standard configuration (I sent a patch to save around 10ms and they fixed an issue with TPM that wasted around 700 ms).

For the Linux Kernel, I used the configuration from Kata (https://github.com/kata-containers/packaging/tree/master/kernel/configs) adding CONFIG_PVH=y.

Finally, I configured QEMU following your tools/build_x86_64.sh

**Comment by yangzhon** [comment]
@stefano-garzarella

Thanks,  with all of those optimizations, the boot time in Qemu is almost same with FC.

**Comment by wkozaczuk** [comment]
@yangzhon Does it mean there is a branch of nemu I can try it? Do I have to build specific version of seabios myself? What are the exact steps to reproduce what you mentioned just above that boot time is almost the same as with FC?

**Comment by yangzhon** [comment]
@stefano-garzarella

I checked the latest seabios, qboot and OVMF bios code, it seems only qboot code has supported PVH now, right ?  thanks!

But from your test as below, this Seabios has enabled PVH feature.
QEMU (q35) + SeaBIOS + vmlinux(PVH)
qemu_init_end: 51.588200
linux_start_kernel: 62.124665 (+10.536465)
linux_start_user: 139.460582 (+77.335917)

**Comment by stefano-garzarella** [comment]
Hi @yangzhon,
SeaBIOS doesn't need to be modified to support PVH, because we created an optionrom in QEMU (as for bzImage).
When you specify a PVH image with -kernel parameter, QEMU tell to SeaBIOS to boot the pvh.bin optionrom (if you specify the bzImage, the linuxboot.bin optionrom will be used). The optionrom will load the kernel using the fw-cfg interface and will jump to it.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
